---
appserver:
- vm6
- vm9
dbserver:
- vm2
fileserver:
- vm5
idxserver:
- vm3
oracle:
- vm3
- vm4
- vm5
sles:
- vm6
ubuntu:
- vm1
- vm2
- vm7
webserver:
- vm1
- vm4
win22:
- vm9
win25:
- vm8
wsus:
- vm8
